// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kabl5v5YjOqOi7IO6kdM2VDMZNnLUnc',
    appId: '1:592839858784:android:ba42596d3d5d05aa578105',
    messagingSenderId: '592839858784',
    projectId: 'radius-7424e',
    databaseURL: 'https://radius-7424e-default-rtdb.firebaseio.com',
    storageBucket: 'radius-7424e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY31NTRKFYoV4jmUCcAXXpRkoHAm_xuOE',
    appId: '1:592839858784:ios:24e5fd18db390a77578105',
    messagingSenderId: '592839858784',
    projectId: 'radius-7424e',
    databaseURL: 'https://radius-7424e-default-rtdb.firebaseio.com',
    storageBucket: 'radius-7424e.appspot.com',
    iosClientId: '592839858784-mvte7r5bb1uq2o8pnecus56ji02ho3i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.radiusApp',
  );
}
